import pytest
import os
import pymupdf as fitz
from backend.pdf_document import PDFDocument

@pytest.fixture
def dummy_pdf(tmp_path):
    pdf_path = tmp_path / "dummy.pdf"
    doc = fitz.open()
    page = doc.new_page(width=500, height=500)
    page.insert_text((50, 50), "Hello World", fontsize=11)
    
    # Add a page that looks like an AI generated one
    page2 = doc.new_page(width=500, height=500)
    page2.insert_text((50, 50), "[[AI_GENERATED_PAGE]] Generated content", fontsize=11)
    
    doc.save(str(pdf_path))
    doc.close()
    return str(pdf_path)

def test_load_pdf(dummy_pdf):
    doc = PDFDocument(dummy_pdf)
    assert doc.doc is not None
    assert doc.page_count == 2
    assert doc.file_path == dummy_pdf

def test_get_page_size(dummy_pdf):
    doc = PDFDocument(dummy_pdf)
    width, height = doc.get_page_size(0)
    assert width == 500.0
    assert height == 500.0

def test_get_page_text(dummy_pdf):
    doc = PDFDocument(dummy_pdf)
    text = doc.get_page_text(0)
    assert "Hello World" in text

def test_get_all_text(dummy_pdf):
    doc = PDFDocument(dummy_pdf)
    all_text = doc.get_all_text()
    assert "Hello World" in all_text
    assert "[[AI_GENERATED_PAGE]]" in all_text

    # Empty document returns empty string
    empty_doc = PDFDocument()
    assert empty_doc.get_all_text() == ""


def test_is_ai_generated(dummy_pdf, tmp_path):
    doc = PDFDocument(dummy_pdf)
    assert doc.is_ai_generated(0) == False
    assert doc.is_ai_generated(1) == True

    # Test that normal text containing 'Generated by' is NOT marked as AI generated
    false_pos_path = tmp_path / "false_pos.pdf"
    d = fitz.open()
    p = d.new_page()
    p.insert_text((50, 50), "This figure was Generated by MATLAB and code generated by authors.")
    d.save(str(false_pos_path))
    d.close()

    fp_doc = PDFDocument(str(false_pos_path))
    assert fp_doc.is_ai_generated(0) == False

def test_append_pdf_file(dummy_pdf, tmp_path):
    # Create a small temp pdf to append
    temp_pdf_path = tmp_path / "temp.pdf"
    temp_doc = fitz.open()
    temp_page = temp_doc.new_page()
    temp_page.insert_text((10, 10), "Appended Content")
    temp_doc.save(str(temp_pdf_path))
    temp_doc.close()
    
    output_path = str(tmp_path / "merged.pdf")
    
    doc = PDFDocument(dummy_pdf)
    success, err = doc.append_pdf_file(str(temp_pdf_path), output_path)
    
    assert success is True
    assert doc.page_count == 3
    assert "Appended Content" in doc.get_page_text(2)
    # The newly appended page is tagged with AI_Generated metadata
    assert doc.is_ai_generated(2) == True


def test_save_document_inplace_backup(dummy_pdf):
    doc = PDFDocument(dummy_pdf)
    assert doc._lock is not None
    
    # Add a highlight and save
    doc.add_highlight_annotation(0, [(50, 50, 100, 70)])
    success, err = doc.save_document()
    
    assert success is True
    assert err == ""
    assert os.path.exists(dummy_pdf)
    assert not os.path.exists(dummy_pdf + ".backup")
    
    # Verify annotation saved and doc is reloadable
    reloaded = PDFDocument(dummy_pdf)
    assert reloaded.page_count == 2
    annots = list(reloaded.doc[0].annots())
    assert len(annots) >= 1

def test_thread_lock_present(dummy_pdf):
    doc = PDFDocument(dummy_pdf)
    import threading
    assert isinstance(doc._lock, type(threading.RLock()))

def test_dirty_state_and_freetext_movement(dummy_pdf):
    doc = PDFDocument(dummy_pdf)
    assert not doc.is_dirty
    
    # Adding FreeText sets dirty
    assert doc.add_freetext_annotation(0, (50, 50, 150, 100), "Hello FreeText")
    assert doc.is_dirty
    
    annot = doc.get_annotation_at_point(0, 60, 60)
    assert annot is not None
    
    # Updating text
    assert doc.update_annotation_text(0, annot, "Updated Text")
    
    # Moving FreeText
    annot = doc.get_annotation_at_point(0, 60, 60)
    assert doc.move_annotation(0, annot, 20, 30)
    
    # Query at new location
    moved_annot = doc.get_annotation_at_point(0, 80, 90)
    assert moved_annot is not None
    
    # Saving resets dirty
    success, _ = doc.save_document()
    assert success
    assert not doc.is_dirty

def test_get_page_image_zoom_capping(dummy_pdf):
    doc = PDFDocument(dummy_pdf)
    assert doc.get_page_image(-1) is None
    assert doc.get_page_image(999) is None

    # Normal zoom (1.0) with dpi_scale 2.0 -> pixel dimensions 500 * 2 = 1000
    img_normal = doc.get_page_image(0, zoom_factor=1.0, dpi_scale=2.0)
    assert img_normal is not None
    assert img_normal.devicePixelRatio() == 2.0
    # In Qt, image.width() on QImage returns physical pixel width
    assert img_normal.width() == 1000
    assert img_normal.height() == 1000

    # High zoom (10.0) with max_zoom=3.0 and dpi_scale 2.0
    # Effective zoom capped at 3.0 -> actual_zoom = 3.0 * 2.0 = 6.0 -> 500 * 6 = 3000 pixels
    # (Without capping, 10.0 * 2.0 = 20.0 -> 10,000 pixels)
    img_capped = doc.get_page_image(0, zoom_factor=10.0, dpi_scale=2.0, max_zoom=3.0)
    assert img_capped is not None
    assert img_capped.width() == 3000
    assert img_capped.height() == 3000

def test_get_page_image_clipped(dummy_pdf):
    doc = PDFDocument(dummy_pdf)
    # Page size is 500x500. Request a 100x150 clip rect at zoom 4.0, dpi_scale 2.0
    clip = (50.0, 50.0, 150.0, 200.0)  # width=100, height=150
    img = doc.get_page_image(0, zoom_factor=4.0, dpi_scale=2.0, clip_rect=clip)
    assert img is not None
    # Physical pixels: 100 * 4.0 * 2.0 = 800 width, 150 * 4.0 * 2.0 = 1200 height
    assert img.width() == 800
    assert img.height() == 1200
    assert img.devicePixelRatio() == 2.0

    # Out of bounds clip returns None
    assert doc.get_page_image(0, clip_rect=(600, 600, 700, 700)) is None

def test_get_page_words_and_cache(dummy_pdf):
    doc = PDFDocument(dummy_pdf)
    words1 = doc.get_page_words(0)
    assert len(words1) > 0
    assert 0 in doc._words_cache
    # Second call returns identical cached list
    words2 = doc.get_page_words(0)
    assert words1 is words2

    # Invalidate single page cache
    doc.invalidate_cache(0)
    assert 0 not in doc._words_cache

    # Verify get_text_range_rects works with cached words
    words = doc.get_page_words(0)
    text, rects = doc.get_text_range_rects(0, (40, 40), (100, 60), words=words)
    assert "Hello" in text

def test_words_cache_lru_eviction(tmp_path):
    pdf_path = tmp_path / "multi_page.pdf"
    doc = fitz.open()
    for i in range(10):
        page = doc.new_page(width=500, height=500)
        page.insert_text((50, 50), f"Page {i} content words", fontsize=11)
    doc.save(str(pdf_path))
    doc.close()

    pdf_doc = PDFDocument(str(pdf_path))
    pdf_doc.MAX_WORDS_CACHE_SIZE = 3

    # Load 0, 1, 2
    pdf_doc.get_page_words(0)
    pdf_doc.get_page_words(1)
    pdf_doc.get_page_words(2)
    assert list(pdf_doc._words_cache.keys()) == [0, 1, 2]

    # Access 0 (becomes most recently used: order [1, 2, 0])
    pdf_doc.get_page_words(0)
    assert list(pdf_doc._words_cache.keys()) == [1, 2, 0]

    # Load 3 -> triggers eviction of oldest (1)
    pdf_doc.get_page_words(3)
    assert len(pdf_doc._words_cache) == 3
    assert list(pdf_doc._words_cache.keys()) == [2, 0, 3]
    assert 1 not in pdf_doc._words_cache


